### ISSUE TITLE
PA Review: Heroku Hosting

### ISSUE THREAD

**Issue by jonabantao** [jonabantao/munchables#2]
- [x] Hosting on Heroku

**Comment by evhumphrey** [comment]
Reopened because when you turn it in, you need to make sure it's production ready on Heroku (so this issue will be a reminder)

We have a reading on this, but includes:

 Remove all console.logs
 Remove everything from window
 Remove Redux logger
https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/helpful_tools/production-ready.md
