### ISSUE TITLE
PA Review: Recipes

### ISSUE THREAD

**Issue by jonabantao** [jonabantao/munchables#3]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentation Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds
- [ ] Protected Routes in "/recipes/:recipeId/edit" and "/recipes/:recipeId/steps/:stepId/edit": Redirects back to home if not author
- [ ] Recipes that have not been "published" will not show up on the main page.

**Comment by evhumphrey** [comment]
- [ ] There is a weird scroll issue; it seems to preserve scroll position between recipes and the show page. Wouldn't try to fix this yet, but it is weird behavior

Styling suggestions: 
- [ ] Lighten text just a bit (so it's not #00000)
- [ ] Lighten background
- [ ] Adjust box shadow and border a bit to make it more subtle/softer (less harsh looking between the thumbnail and background)
- [ ] Adjust position of text in the thumbnails, it looks a little cramped and unbalanced right now
- [ ] Increase vertical margin between thumbnails

Screenshot:
![screen shot 2018-02-06 at 3 45 06 pm](https://user-images.githubusercontent.com/6361824/35890508-ea8be00a-0b54-11e8-94a7-923e89a6801e.png)

**Comment by evhumphrey** [comment]
Awesome!

**Comment by evhumphrey** [comment]
Reopened because when you turn it in, you need to make sure it's production ready on Heroku (so this issue will be a reminder)

We have a reading on this, but includes:

 Remove all console.logs
 Remove everything from window
 Remove Redux logger
https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/helpful_tools/production-ready.md
